steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-image', '.']

  # Push image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'backend-service',
        '--image', 'gcr.io/$PROJECT_ID/backend-image',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated'
      ]
